spring:
  main:
    allow-bean-definition-overriding: true
  application:  #http注册
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.102:8848
server:
  port: 10101
dubbo:
  application:  #dubbo注册
    name: provider
  registry:
    address: nacos://192.168.8.102:8848
  scan:
    base-packages: com.wandm.dubbo.provider.service
  #protocol:  #报错，在ProviderApplication注入配置
  #  port: 20880

management:
  endpoints:
    web:
      exposure:
        include: "*"
