spring:
  main:
    allow-bean-definition-overriding: true
  application:  #http注册
    name: spring-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.102:8848
server:
  port: 10201
dubbo:
  application:  #dubbo注册
    name: dubbo-consumer
  registry:
    address: nacos://192.168.8.102:8848
  scan:
    base-packages: com.wandm.dubbo.consumer.service

management:
  endpoints:
    web:
      exposure:
        include: "*"
